### ISSUE TITLE
Plugin Manager integration

### ISSUE THREAD

**Issue by maraf** [otmopo3/GitLabGitExtensionsPlugins#4]
Hi, I would like to let you know that we have created a way to distribute and install Git Extensions plugins.

So if you still use this plugin, you can simply bundle it as a nuget package and install it to Git Extensions through [Plugin Manager](https://github.com/gitextensions/gitextensions.pluginmanager). We have a [template repository](https://github.com/gitextensions/gitextensions.plugintemplate) which can guide you or I would gladly help, let me know.

**Comment by otmopo3** [comment]
Thanks, I'll look into that. Actually I have some problems. GUI is very raw )) And plugin usually stops working when GitExtensions updates. Publishing not only code, but binaries on nuget means more responsibility, as users can download plugin and crash gitextensions. Not sure if it looks good. I hope this will be motivation for me to make plugin better and then publish it as ready-to-use plugin ))
